import {
  IconAlertCircle,
  IconArrowLeft,
  IconArrowRight,
  IconArrowsSort,
  IconBinaryTree,
  IconBraces,
  IconBrackets,
  IconBracketsAngle,
  IconChartBar,
  IconCheck,
  IconChevronDown,
  IconChevronLeft,
  IconChevronRight,
  IconChevronUp,
  IconCircle,
  IconCircleDot,
  IconCode,
  IconComponents,
  IconCopy,
  IconDatabase,
  IconDeviceDesktop,
  IconDots,
  IconEyeCheck,
  IconEyeX,
  IconFile,
  IconFileCode,
  IconFileDescription,
  IconFileSearch,
  IconFolderCode,
  IconFunction,
  IconGlobe,
  IconInfoCircle,
  IconKey,
  IconLayoutDashboard,
  IconLocationCode,
  IconMoon,
  IconPackage,
  IconPercentage,
  IconPuzzle,
  IconQuotes,
  IconSearch,
  IconSearchOff,
  IconSortAscending,
  IconSortDescending,
  IconSun,
  IconTag,
  IconToggleLeft,
  IconUsers,
  IconX,
  type TablerIcon,
} from '@tabler/icons-react'

import type { IconName } from './types.js'

/** Registry mapping icon names to Tabler icon components */
export const ICON_REGISTRY: Record<IconName, TablerIcon> = {
  // Navigation
  'chevron-down': IconChevronDown,
  'chevron-up': IconChevronUp,
  'chevron-right': IconChevronRight,
  'chevron-left': IconChevronLeft,
  'arrow-left': IconArrowLeft,
  'arrow-right': IconArrowRight,
  // Actions
  search: IconSearch,
  'search-off': IconSearchOff,
  close: IconX,
  check: IconCheck,
  copy: IconCopy,
  // Status
  'alert-circle': IconAlertCircle,
  'info-circle': IconInfoCircle,
  resolved: IconEyeCheck,
  unresolved: IconEyeX,
  pending: IconCircleDot,
  empty: IconCircle,
  // Sorting
  'sort-asc': IconSortAscending,
  'sort-desc': IconSortDescending,
  'sort-none': IconArrowsSort,
  // Theme
  sun: IconSun,
  moon: IconMoon,
  desktop: IconDeviceDesktop,
  // Entity
  package: IconPackage,
  component: IconPuzzle,
  hierarchy: IconBinaryTree,
  file: IconFile,
  'file-code': IconFileCode,
  'file-search': IconFileSearch,
  'file-description': IconFileDescription,
  'location-code': IconLocationCode,
  external: IconGlobe,
  internal: IconFolderCode,
  // Code
  code: IconCode,
  element: IconBracketsAngle,
  brackets: IconBrackets,
  dots: IconDots,
  toggle: IconToggleLeft,
  percentage: IconPercentage,
  prop: IconKey,
  'prop-name': IconTag,
  'prop-value': IconBraces,
  string: IconQuotes,
  function: IconFunction,
  // Data
  dashboard: IconLayoutDashboard,
  database: IconDatabase,
  chart: IconChartBar,
  users: IconUsers,
  components: IconComponents,
}
