import {
  IconAlertCircle,
  IconAlertTriangle,
  IconArrowLeft,
  IconArrowRight,
  IconArrowsSort,
  IconBinaryTree,
  IconBolt,
  IconBook,
  IconBookmark,
  IconBraces,
  IconBrackets,
  IconBracketsAngle,
  IconBrandGithub,
  IconBug,
  IconCalendar,
  IconChartBar,
  IconCheck,
  IconChevronDown,
  IconChevronLeft,
  IconChevronRight,
  IconChevronUp,
  IconCircle,
  IconCircleCheck,
  IconCircleDot,
  IconCircleX,
  IconClock,
  IconCode,
  IconCoffee,
  IconComponents,
  IconCopy,
  IconDatabase,
  IconDeviceDesktop,
  IconDots,
  IconDotsVertical,
  IconDownload,
  IconEdit,
  IconExternalLink,
  IconEye,
  IconEyeCheck,
  IconEyeOff,
  IconEyeX,
  IconFile,
  IconFileCode,
  IconFileDescription,
  IconFileSearch,
  IconFileText,
  IconFilter,
  IconFolder,
  IconFolderCode,
  IconFunction,
  IconGitBranch,
  IconGitMerge,
  IconGitPullRequest,
  IconGlobe,
  IconHammer,
  IconHash,
  IconHelp,
  IconHexagonLetterL,
  IconHistory,
  IconHourglass,
  IconInfoCircle,
  IconKey,
  IconLayoutDashboard,
  IconLink,
  IconLoader2,
  IconLocationCode,
  IconLock,
  IconMenu2,
  IconMessage,
  IconMinus,
  IconMoon,
  IconPackage,
  IconPalette,
  IconPencil,
  IconPercentage,
  IconPlayerPlay,
  IconPlayerStop,
  IconPlus,
  IconPrompt,
  IconPuzzle,
  IconQuotes,
  IconRefresh,
  IconRobot,
  IconRocket,
  IconSearch,
  IconSearchOff,
  IconSettings,
  IconSitemap,
  IconSortAscending,
  IconSortDescending,
  IconSparkles,
  IconSun,
  IconTag,
  IconTerminal2,
  IconTestPipe,
  IconToggleLeft,
  IconTool,
  IconTrash,
  IconUpload,
  IconUsers,
  IconWand,
  IconX,
  type TablerIcon,
} from '@tabler/icons-react'

import type { IconName } from './types.js'

/** Registry mapping icon names to Tabler icon components */
export const ICON_REGISTRY: Record<IconName, TablerIcon> = {
  // Navigation
  'chevron-down': IconChevronDown,
  'chevron-up': IconChevronUp,
  'chevron-right': IconChevronRight,
  'chevron-left': IconChevronLeft,
  'arrow-left': IconArrowLeft,
  'arrow-right': IconArrowRight,
  // Actions
  search: IconSearch,
  'search-off': IconSearchOff,
  close: IconX,
  check: IconCheck,
  copy: IconCopy,
  plus: IconPlus,
  minus: IconMinus,
  trash: IconTrash,
  settings: IconSettings,
  menu: IconMenu2,
  filter: IconFilter,
  link: IconLink,
  upload: IconUpload,
  download: IconDownload,
  'eye-off': IconEyeOff,
  lock: IconLock,
  help: IconHelp,
  bookmark: IconBookmark,
  'dots-vertical': IconDotsVertical,
  // Status
  'alert-circle': IconAlertCircle,
  'info-circle': IconInfoCircle,
  resolved: IconEyeCheck,
  unresolved: IconEyeX,
  pending: IconCircleDot,
  empty: IconCircle,
  success: IconCircleCheck,
  error: IconCircleX,
  warning: IconAlertTriangle,
  // Sorting
  'sort-asc': IconSortAscending,
  'sort-desc': IconSortDescending,
  'sort-none': IconArrowsSort,
  // Theme
  sun: IconSun,
  moon: IconMoon,
  desktop: IconDeviceDesktop,
  // Entity
  package: IconPackage,
  component: IconPuzzle,
  hierarchy: IconBinaryTree,
  file: IconFile,
  'file-code': IconFileCode,
  'file-search': IconFileSearch,
  'file-description': IconFileDescription,
  'location-code': IconLocationCode,
  external: IconGlobe,
  'external-link': IconExternalLink,
  internal: IconFolderCode,
  folder: IconFolder,
  hash: IconHash,
  // Code
  code: IconCode,
  element: IconBracketsAngle,
  brackets: IconBrackets,
  dots: IconDots,
  toggle: IconToggleLeft,
  percentage: IconPercentage,
  prop: IconKey,
  'prop-name': IconTag,
  'prop-value': IconBraces,
  string: IconQuotes,
  function: IconFunction,
  // Data
  dashboard: IconLayoutDashboard,
  database: IconDatabase,
  chart: IconChartBar,
  users: IconUsers,
  components: IconComponents,
  calendar: IconCalendar,
  clock: IconClock,
  history: IconHistory,
  // Agentic
  agent: IconRobot,
  orchestrator: IconSitemap,
  // Agentic - Actions
  write: IconPencil,
  read: IconBook,
  edit: IconEdit,
  tool: IconTool,
  text: IconFileText,
  prompt: IconPrompt,
  // Agentic - Status
  idle: IconCoffee,
  waiting: IconHourglass,
  implement: IconHammer,
  refine: IconWand,
  working: IconLoader2,
  watching: IconEye,
  // Agentic - Orchestration
  message: IconMessage,
  polling: IconRefresh,
  start: IconPlayerPlay,
  stop: IconPlayerStop,
  // Brand & Integrations
  github: IconBrandGithub,
  linear: IconHexagonLetterL,
  // Developer Tools
  terminal: IconTerminal2,
  'git-branch': IconGitBranch,
  'git-merge': IconGitMerge,
  'git-pull-request': IconGitPullRequest,
  bug: IconBug,
  'test-tube': IconTestPipe,
  rocket: IconRocket,
  sparkles: IconSparkles,
  bolt: IconBolt,
  palette: IconPalette,
}
