import '@fontsource/ibm-plex-mono'
import '@fontsource-variable/geist'
import '@fontsource-variable/geist-mono'
import '@fontsource-variable/ibm-plex-sans'
import '@fontsource-variable/instrument-sans'
